version: "3.0"

services:
  gitlab:
    image: gitlab/gitlab-ce
    restart: unless-stopped
    shm_size: 256m
    logging:
      driver: "journald"
    ports:
      # - "443:443"
      - "$GITLAB_HTTP_PORT:$GITLAB_HTTP_PORT"
      - "$GITLAB_SSH_PORT:22"
    env_file:
      - .env
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    volumes:
      - $GITLAB_HOME/config:/etc/gitlab
      - $GITLAB_HOME/logs:/var/log/gitlab
      - $GITLAB_HOME/data:/var/opt/gitlab
      - ./gitlab.rb:/omnibus_config.rb
