services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    deploy:
        mode: replicated
        replicas: 4
    depends_on:
        - gitlab
    ports:
      - 8093:8093
    environment:
        TZ: America/Sao_Paulo
        #CA_CERTIFICATES_PATH: $GITLAB_HOME/config/trusted-certs
        #CI_SERVER_URL: https://$GITLAB_HOST/
    volumes:
        - $GITLAB_HOME/config/gitlab-runner:/etc/gitlab-runner
        - /var/run/docker.sock:/var/run/docker.sock
        # - ./config.toml:/config.toml
        # - ./config.template.toml:/config.template.toml
